apriltags:
  - id: 200
    x: 0.17
    y: 0.17
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0.75
  - id: 201
    x: 1.65
    y: 0.17
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1.25
  - id: 94
    x: 1.65
    y: 2.84
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1.75
  - id: 93
    x: 0.17
    y: 2.84
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0.25
  - id: 153
    x: 1.75
    y: 1.252
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0
  - id: 133
    x: 1.253
    y: 1.755
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 143
    x: 1.253
    y: 1.755
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 58
    x: 0.574
    y: 1.259
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0
  - id: 62
    x: 0.075
    y: 1.755
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 1
  - id: 169
    x: 0.574
    y: 1.755
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: 0.5
  - id: 162
    x: 1.253
    y: 1.253
    z: 0.08
    yaw: -0.5
    pitch: 0
    roll: -0.5
