FROM duckietown/dt-duckiebot-interface:daffy-arm64v8

WORKDIR /color_detector_dir

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY color_detector.py .

CMD python3 ./color_detector.py
